# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'A designer, developer and entrepreneur.'
email: hqmank@gmail.com
# Content
excerpt_link:  More

# Miscellaneous
rss:


